# Autogenerated wrapper script for cmocka_jll for powerpc64le-linux-gnu
export libcmocka

JLLWrappers.@generate_wrapper_header("cmocka")
JLLWrappers.@declare_library_product(libcmocka, "libcmocka.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcmocka,
        "lib/libcmocka.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
