# Autogenerated wrapper script for cmocka_jll for x86_64-apple-darwin
export libcmocka

JLLWrappers.@generate_wrapper_header("cmocka")
JLLWrappers.@declare_library_product(libcmocka, "@rpath/libcmocka.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcmocka,
        "lib/libcmocka.0.7.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
